# Date: 2019-113
# Author: toddlerya@gmail.com
version: '3'
services:
  nginx:
    container_name: pypi_nginx
    image: nginx:1.15.2-alpine
    networks:
      pypi_net:
        ipv4_address: 172.21.0.2
    ports:
    - "8898:80"
    restart: always
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "./nginx/conf:/etc/nginx/conf.d"
    - "./nginx/logs:/var/log/nginx"
  pypiserver:
    container_name: pypiserver
    image: evi1/pypiserver:1.2.5
    networks:
      pypi_net:
        ipv4_address: 172.21.0.3
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - ./pypiserver/pypi_data/packages:/data/packages
    - ./pypiserver/pypi_data/logs:/data/logs
    - ./pypiserver/pypi_data/conf:/data/conf
    # - /home/evi1/pypi/.htpasswd:/data/.htpasswd
    ports:
    - 8899:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080 || exit 1"]
      interval: 60m
      timeout: 10s
      retries: 3
    command: -v --log-file=/data/logs/pypiserver.log -P . -a . /data/packages
  pypimanager:
    container_name: pypimanager
    image: evi1/pypiserver-manager:1.0.0
    networks:
      pypi_net:
        ipv4_address: 172.21.0.4
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - ./pypimanager/fixtures/auth_user.json:/web/fixtures/auth_user.json
    - ./pypiserver/db:/web/db
    ports:
    - 3134:5000
    environment:
    - PYPI_HOST=${HOST_IP}
    - PYPI_PORT=8898
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5000 || exit 1"]
      interval: 60m
      timeout: 10s
      retries: 3
networks:
  pypi_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16